require('dotenv').config();
const { env } = process;
const DB_USERNAME = env.DB_USERNAME;
const DB_PASSWORD = env.DB_PASSWORD;
const DB_NAME = env.DB_NAME;
const DB_HOST = env.DB_HOST;
const DB_PORT = env.DB_PORT;

const FRONTEND_URL = env.FRONTEND_URL || 'http://localhost:4200';
const PORT = env.PORT;

const JWT_SECRET_KEY = env.JWT_KEY;
const EXPIRE_TIME = env.EXPIRE_TIME;
const REFRESH_EXPIRE_TIME = env.REFRESH_EXPIRE_TIME;
const EMAIL_ADMIN = env.EMAIL_ADMIN;
const EMAIL_PASSWORD = env.EMAIL_PASSWORD;
const EMAIL_HOST = env.EMAIL_HOST;
const EMAIL_PORT = env.EMAIL_PORT;
const EMAIL_FROM = env.EMAIL_FROM;
const TYPE = env.TYPE
const PROJECT_ID = env.PROJECT_ID
const PRIVATE_KEY_ID = env.PRIVATE_KEY_ID
const PRIVATE_KEY = env.PRIVATE_KEY
const CLIENT_EMAIL = env.CLIENT_EMAIL
const CLIENT_ID = env.CLIENT_ID
const AUTH_URI = env.AUTH_URI
const TOKEN_URI = env.TOKEN_URI
const AUTH_PROVIDER_X509_CERT_URL = env.AUTH_PROVIDER_X509_CERT_URL
const CLIENT_X509_CERT_URL = env.CLIENT_X509_CERT_URL
const UNIVERSE_DOMAIN = env.UNIVERSE_DOMAIN
const CASH_RANK_BRONZE = env.CASH_RANK_BRONZE
const CASH_RANK_SILVER = env.CASH_RANK_SILVER
const CASH_RANK_GOLD = env.CASH_RANK_GOLD
const PAYPAL_CLIENT_KEY = env.PAYPAL_CLIENT_KEY
const PAYPAL_SECRET_KEY = env.PAYPAL_SECRET_KEY

export const Env = {
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME,
  DB_HOST,
  DB_PORT,
  FRONTEND_URL,
  PORT,
  JWT_SECRET_KEY,
  EXPIRE_TIME,
  REFRESH_EXPIRE_TIME,
  EMAIL_ADMIN,
  EMAIL_PASSWORD,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_FROM,
  TYPE,
  PROJECT_ID,
  PRIVATE_KEY_ID,
  PRIVATE_KEY,
  CLIENT_EMAIL,
  CLIENT_ID,
  AUTH_URI,
  TOKEN_URI,
  AUTH_PROVIDER_X509_CERT_URL,
  CLIENT_X509_CERT_URL,
  UNIVERSE_DOMAIN,
  CASH_RANK_BRONZE,
  CASH_RANK_SILVER,
  CASH_RANK_GOLD,
  PAYPAL_CLIENT_KEY,
  PAYPAL_SECRET_KEY
};
